### ISSUE TITLE
کتاب به شکل یک وبسایت

### ISSUE THREAD

**Issue by ghost** [mthri/dfp-persian#133]
سلام .
ایا تمایل دارید که این کتاب به صورت یک وبسایت در گیتهاب دیپلوی بشه ؟

**Comment by mthri** [comment]
سلام
چرا که نه!

**Comment by smsameet** [comment]
من قصد دارم با nextjs این کار رو انجام بدم .
ایا تکنولوژی مشخصی مورد نظر شما هست ؟
وهمچنین تم یا نمونه ی مشخصی هم مورد نظرتون نیست ؟

**Comment by mthri** [comment]
ممنون
نه، مورد خاصی مدنظرم نیست

**Comment by smsameet** [comment]
درود صفحه ی اول پروژه اماده شده . اسم دامنه ( اسم ریپوزیتوری ) رو چی بگذارم ؟

**Comment by smsameet** [comment]
https://github.com/smsameet/django-for-professionals
https://smsameet.github.io/django-for-professionals/
بعدا هم میشه اسم رو تغییر داد , مشکل اساسی نیست .

**Comment by mthri** [comment]
عالی

**Comment by smsameet** [comment]
درود !
تمامی سرفصل ها داخل فهرست قرار گفتن ( پوش نکردم ) میخواستم بپرسم که کدوم یکی از این ها برای فهرست بهترن و اینکه فهرست رو به فارسی بنویسم ( مثل الان ) یا انگلیسی .

![one](https://s2.uupload.ir/files/2023-03-13_14-03_crq8.png)
---
![two](https://s2.uupload.ir/files/2023-03-13_14-03_1_pqsj.png)

**Comment by smsameet** [comment]
با سلام .
وقت به خیر .
عذر خواهی میکنم بابت این تاخیری که پیش اومد .
پروژه رو به حد معقولی رسوندم . ببینید چطور شده فعلا .
https://django-for-professionals-ir.vercel.app/
اگه جایی مشکل بود ( توی استایل ها ) بگید فیکس کنم .

**Comment by mthri** [comment]
سلام
خیلی خوب هست،‌اگر دوستداری داخل گروه لینکش رو بزارم بقیه بچه ها نظرشون رو بگن

**Comment by smsameet** [comment]
مشکلی نیست ! فقط گروه ؟

**Comment by mthri** [comment]
متوجه منظورت نشدم :)‌ پیشنهادم خوب بود یا بد بود؟

**Comment by smsameet** [comment]
نه مشکلی نیست . منظور این بود که همون گروه تلگرامی بودش ؟

**Comment by mthri** [comment]
اره، داخل کانال هم میتونم بزارم
اگر میتونی تلگرام بهم پیام بده، آیدیم a_motahari

**Comment by MEgooneh** [comment]
سایت خراب شده. لطفا بجای vercel یک برنچ pages باز کنید بنظر استیبل تر میاد.

**Comment by mthri** [comment]
> سایت خراب شده. لطفا بجای vercel یک برنچ pages باز کنید بنظر استیبل تر میاد.
اگر میتونید این کا رو خودتون انجام بدید بهتون دسترسی بدم

**Comment by MEgooneh** [comment]
بنده خدایی که با nextjs نوشته بود سورس کدشو داد یا فقط لینک داد ؟ الانم دیلیت اکانت زده.

**Comment by mthri** [comment]
فقط لینک داد
