### ISSUE TITLE
ترجمه فصل ۶

### ISSUE THREAD

**Issue by phpreza** [mthri/dfp-persian#25]
با ترجمه فصل ۶ در خدمتتون هستم
مبحث static assets

**Comment by mthri** [comment]
موردی نداری، منتهی چون تا این اواخر کسی قبول نکرد، خانم [موسوی](https://github.com/cemusavi) قبول زحمت کردن
اگر امکانش هست داخل گروه تلگرامی مطرح کنید فکر کنم اونجا بتونیم اوکیش کنیم
