### ISSUE TITLE
Rename Directories

### ISSUE THREAD

**Issue by BlackIQ** [mthri/dfp-persian#26]
به صورت عادی وقتی شما از عدد 1 شروع میکنید به نام گذاری، وقتی به عدد ده میرسید ترتیب نام ها تغییر میکند.
به همین دلیل برای نامگذاری بهتره که از 01 شروع شود.
یعنی 01 و 02 و 03 و 04 و غیره. اینطوری بعد از 09 وقتی به 10 میرسید ترتیب پوشه ها مرتب میشوند.

اگه مایل باشید این نامگذاری ها رو بنده تو یه PR درست کنم.

**Comment by themaximalist** [comment]
بسیار عالی
 به این نکته توجه نکرده بودیم
اگر خواستید پول کنید حتما رسیدگی میکنیم
