### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by BlackIQ** [mthri/dfp-persian#30]
To read the book online in every devices you can use Github Pages cause in this case you can use markdown files too.

Also you can create a docs directory and create it with html and css files. One more point is that you can connect it to a domain or even a subdomain.

Amir.

**Comment by KomeilParseh** [comment]
> To read the book online in every devices you can use Github Pages cause in this case you can use markdown files too.
> 
> Also you can create a docs directory and create it with html and css files. One more point is that you can connect it to a domain or even a subdomain.
> 
> Amir.

Yes, I agree and it can be done even easier, that is, you can use pre-made templates.

**Comment by themaximalist** [comment]
Hello Dears. 

thanks for sharing you opinion, this book is under translation and after completing this stage we will consider to use GitHub pages for sure.  

best wishes.

Omid
